#!/bin/bash
# nft-safe-reload
# Reload nftables configuration and wait for user confirmation.
# After a timeout the previous configuration is restored.
# Original Author: https://sanjuroe.dev/nft-safe-reload
# This version containes proper shell quoting.

save_file="$(mktemp)"

cleanup() {
        rm -f "$save_file"
}

trap "cleanup" EXIT

RULES="/etc/nftables.conf"
TIMEOUT=30

read_yesno_with_timeout() {
        read -t "$TIMEOUT" yn 2> /dev/null

        case "$yn" in
                y|Y)
                        return 0
                        ;;
                *)
                        return 1
                        ;;
        esac
}

save() {
        echo "flush ruleset" >> "$save_file"
        nft list ruleset >> "$save_file"
}

apply() {
        nft -f "$RULES"
}

restore() {
        nft -f "$save_file"
}

save

if apply; then
        echo -n "Do you want to accept the new firewall configuration? [y/n] "
        if read_yesno_with_timeout; then
                echo "Accepted new configuration"
        else
                restore
                echo "Restored old configuration"
                exit 2
        fi
fi

